/* AUTO-GENERATED by scripts/generate-catalog.mjs. Do not edit by hand. */

export type PatternShape =
  | 'arcs'
  | 'circle'
  | 'clover'
  | 'domes'
  | 'fans'
  | 'leaves'
  | 'plus'
  | 'quads'
  | 'square'
  | 'x';

export type PatternColor = 'blue' | 'green' | 'red' | 'yellow';

export type PatternScheme =
  | 'blue-on-white'
  | 'green-on-white'
  | 'red-on-white'
  | 'yellow-on-white'
  | 'white-on-blue'
  | 'white-on-green'
  | 'white-on-red'
  | 'white-on-yellow';

export interface PatternEntry {
  shape: PatternShape;
  scheme: PatternScheme;
  fg: string;
  bg: string;
  svg: string;
}

export const CATALOG: Record<string, PatternEntry> = {
  'arcs-blue-on-white': {
    shape: 'arcs',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_17)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="#3A6DC5"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="#3A6DC5"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="#3A6DC5"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="#3A6DC5"/> </g> <defs> <clipPath id="clip0_5_17"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-green-on-white': {
    shape: 'arcs',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_23)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="#0F8657"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="#0F8657"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="#0F8657"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="#0F8657"/> </g> <defs> <clipPath id="clip0_5_23"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-red-on-white': {
    shape: 'arcs',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_21)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="#F94141"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="#F94141"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="#F94141"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="#F94141"/> </g> <defs> <clipPath id="clip0_5_21"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-white-on-blue': {
    shape: 'arcs',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_9)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="white"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="white"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="white"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_9"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-white-on-green': {
    shape: 'arcs',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_15)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="white"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="white"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="white"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_15"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-white-on-red': {
    shape: 'arcs',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_13)"> <rect width="100" height="100" fill="#F94141"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="white"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="white"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="white"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_13"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-white-on-yellow': {
    shape: 'arcs',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_11)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="white"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="white"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="white"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_11"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'arcs-yellow-on-white': {
    shape: 'arcs',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_19)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H2C29.6142 0 52 22.3858 52 50V52H50C22.3858 52 0 29.6142 0 2V0Z" fill="#F7BF33"/> <path d="M0 100H2C29.6142 100 52 77.6142 52 50V48H50C22.3858 48 0 70.3858 0 98V100Z" fill="#F7BF33"/> <path d="M100 0H98C70.3858 0 48 22.3858 48 50V52H50C77.6142 52 100 29.6142 100 2V0Z" fill="#F7BF33"/> <path d="M100 100H98C70.3858 100 48 77.6142 48 50V48H50C77.6142 48 100 70.3858 100 98V100Z" fill="#F7BF33"/> </g> <defs> <clipPath id="clip0_5_19"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-blue-on-white': {
    shape: 'circle',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_51)"> <rect width="100" height="100" fill="white"/> <circle cx="50" cy="50" r="40" stroke="#3A6DC5" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_51"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-green-on-white': {
    shape: 'circle',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_57)"> <rect width="100" height="100" fill="white"/> <circle cx="50" cy="50" r="40" stroke="#0F8657" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_57"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-red-on-white': {
    shape: 'circle',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_55)"> <rect width="100" height="100" fill="white"/> <circle cx="50" cy="50" r="40" stroke="#F94141" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_55"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-white-on-blue': {
    shape: 'circle',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_43)"> <rect width="100" height="100" fill="#3A6DC5"/> <circle cx="50" cy="50" r="40" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_43"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-white-on-green': {
    shape: 'circle',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_49)"> <rect width="100" height="100" fill="#0F8657"/> <circle cx="50" cy="50" r="40" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_49"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-white-on-red': {
    shape: 'circle',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_47)"> <rect width="100" height="100" fill="#F94141"/> <circle cx="50" cy="50" r="40" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_47"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-white-on-yellow': {
    shape: 'circle',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_45)"> <rect width="100" height="100" fill="#F7BF33"/> <circle cx="50" cy="50" r="40" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_45"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'circle-yellow-on-white': {
    shape: 'circle',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_53)"> <rect width="100" height="100" fill="white"/> <circle cx="50" cy="50" r="40" stroke="#F7BF33" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_53"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-blue-on-white': {
    shape: 'clover',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_169)"> <rect width="100" height="100" fill="white"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="#3A6DC5"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="#3A6DC5"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="#3A6DC5"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="#3A6DC5"/> </g> <defs> <clipPath id="clip0_5_169"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-green-on-white': {
    shape: 'clover',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_184)"> <rect width="100" height="100" fill="white"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="#0F8657"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="#0F8657"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="#0F8657"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="#0F8657"/> </g> <defs> <clipPath id="clip0_5_184"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-red-on-white': {
    shape: 'clover',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_179)"> <rect width="100" height="100" fill="white"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="#F94141"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="#F94141"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="#F94141"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="#F94141"/> </g> <defs> <clipPath id="clip0_5_179"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-white-on-blue': {
    shape: 'clover',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_189)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="white"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="white"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="white"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_189"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-white-on-green': {
    shape: 'clover',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_194)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="white"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="white"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="white"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_194"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-white-on-red': {
    shape: 'clover',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_199)"> <rect width="100" height="100" fill="#F94141"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="white"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="white"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="white"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_199"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-white-on-yellow': {
    shape: 'clover',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_204)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="white"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="white"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="white"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_204"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'clover-yellow-on-white': {
    shape: 'clover',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_174)"> <rect width="100" height="100" fill="white"/> <path d="M50 50H25C11.1929 50 0 38.8071 0 25C0 11.1929 11.1929 0 25 0C38.8071 0 50 11.1929 50 25V50Z" fill="#F7BF33"/> <path d="M50 50V25C50 11.1929 61.1929 0 75 0C88.8071 0 100 11.1929 100 25C100 38.8071 88.8071 50 75 50H50Z" fill="#F7BF33"/> <path d="M50 50H25C11.1929 50 0 61.1929 0 75C0 88.8071 11.1929 100 25 100C38.8071 100 50 88.8071 50 75V50Z" fill="#F7BF33"/> <path d="M50 50V75C50 88.8071 61.1929 100 75 100C88.8071 100 100 88.8071 100 75C100 61.1929 88.8071 50 75 50H50Z" fill="#F7BF33"/> </g> <defs> <clipPath id="clip0_5_174"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-blue-on-white': {
    shape: 'domes',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_77)"> <rect width="100" height="100" fill="white"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="#3A6DC5"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="#3A6DC5"/> </g> <defs> <clipPath id="clip0_5_77"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-green-on-white': {
    shape: 'domes',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_83)"> <rect width="100" height="100" fill="white"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="#0F8657"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="#0F8657"/> </g> <defs> <clipPath id="clip0_5_83"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-red-on-white': {
    shape: 'domes',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_81)"> <rect width="100" height="100" fill="white"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="#F94141"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="#F94141"/> </g> <defs> <clipPath id="clip0_5_81"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-white-on-blue': {
    shape: 'domes',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_85)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="white"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_85"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-white-on-green': {
    shape: 'domes',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_87)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="white"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_87"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-white-on-red': {
    shape: 'domes',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_91)"> <rect width="100" height="100" fill="#F94141"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="white"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_91"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-white-on-yellow': {
    shape: 'domes',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_89)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="white"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_89"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'domes-yellow-on-white': {
    shape: 'domes',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_79)"> <rect width="100" height="100" fill="white"/> <path d="M100 0C100 27.6142 77.6142 50 50 50C22.3858 50 0 27.6142 0 0C0 -27.6142 22.3858 -50 50 -50C77.6142 -50 100 -27.6142 100 0Z" fill="#F7BF33"/> <path d="M100 100C100 127.614 77.6142 150 50 150C22.3858 150 0 127.614 0 100C0 72.3858 22.3858 50 50 50C77.6142 50 100 72.3858 100 100Z" fill="#F7BF33"/> </g> <defs> <clipPath id="clip0_5_79"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-blue-on-white': {
    shape: 'fans',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_94)"> <rect width="100" height="100" fill="white"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="#3A6DC5"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="#3A6DC5"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="#3A6DC5"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="#3A6DC5"/> </g> <defs> <clipPath id="clip0_5_94"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-green-on-white': {
    shape: 'fans',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_100)"> <rect width="100" height="100" fill="white"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="#0F8657"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="#0F8657"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="#0F8657"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="#0F8657"/> </g> <defs> <clipPath id="clip0_5_100"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-red-on-white': {
    shape: 'fans',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_98)"> <rect width="100" height="100" fill="white"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="#F94141"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="#F94141"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="#F94141"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="#F94141"/> </g> <defs> <clipPath id="clip0_5_98"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-white-on-blue': {
    shape: 'fans',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_102)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="white"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="white"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="white"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_102"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-white-on-green': {
    shape: 'fans',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_104)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="white"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="white"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="white"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_104"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-white-on-red': {
    shape: 'fans',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_106)"> <rect width="100" height="100" fill="#F94141"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="white"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="white"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="white"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_106"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-white-on-yellow': {
    shape: 'fans',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_108)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="white"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="white"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="white"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_108"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'fans-yellow-on-white': {
    shape: 'fans',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_96)"> <rect width="100" height="100" fill="white"/> <path d="M150 0C150 27.6142 127.614 50 100 50C72.3858 50 50 27.6142 50 0C50 -27.6142 72.3858 -50 100 -50C127.614 -50 150 -27.6142 150 0Z" fill="#F7BF33"/> <path d="M150 100C150 127.614 127.614 150 100 150C72.3858 150 50 127.614 50 100C50 72.3858 72.3858 50 100 50C127.614 50 150 72.3858 150 100Z" fill="#F7BF33"/> <path d="M50 0C50 27.6142 27.6142 50 0 50C-27.6142 50 -50 27.6142 -50 0C-50 -27.6142 -27.6142 -50 0 -50C27.6142 -50 50 -27.6142 50 0Z" fill="#F7BF33"/> <path d="M50 100C50 127.614 27.6142 150 0 150C-27.6142 150 -50 127.614 -50 100C-50 72.3858 -27.6142 50 0 50C27.6142 50 50 72.3858 50 100Z" fill="#F7BF33"/> </g> <defs> <clipPath id="clip0_5_96"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-blue-on-white': {
    shape: 'leaves',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_119)"> <rect width="100" height="100" fill="white"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="#3A6DC5"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="#3A6DC5"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="#3A6DC5"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="#3A6DC5"/> </g> <defs> <clipPath id="clip0_5_119"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-green-on-white': {
    shape: 'leaves',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_121)"> <rect width="100" height="100" fill="white"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="#0F8657"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="#0F8657"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="#0F8657"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="#0F8657"/> </g> <defs> <clipPath id="clip0_5_121"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-red-on-white': {
    shape: 'leaves',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_123)"> <rect width="100" height="100" fill="white"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="#F94141"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="#F94141"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="#F94141"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="#F94141"/> </g> <defs> <clipPath id="clip0_5_123"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-white-on-blue': {
    shape: 'leaves',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_111)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="white"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="white"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="white"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_111"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-white-on-green': {
    shape: 'leaves',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_117)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="white"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="white"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="white"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_117"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-white-on-red': {
    shape: 'leaves',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_115)"> <rect width="100" height="100" fill="#F94141"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="white"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="white"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="white"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_115"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-white-on-yellow': {
    shape: 'leaves',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_113)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="white"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="white"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="white"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_113"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'leaves-yellow-on-white': {
    shape: 'leaves',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_125)"> <rect width="100" height="100" fill="white"/> <path d="M0 0C27.6142 0 50 22.3858 50 50C22.3858 50 0 27.6142 0 0Z" fill="#F7BF33"/> <path d="M0 100C27.6142 100 50 77.6142 50 50C22.3858 50 0 72.3858 0 100Z" fill="#F7BF33"/> <path d="M50 0C77.6142 0 100 22.3858 100 50C72.3858 50 50 27.6142 50 0Z" fill="#F7BF33"/> <path d="M50 100C77.6142 100 100 77.6142 100 50C72.3858 50 50 72.3858 50 100Z" fill="#F7BF33"/> </g> <defs> <clipPath id="clip0_5_125"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-blue-on-white': {
    shape: 'plus',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_407)"> <rect width="100" height="100" fill="white"/> <path d="M50 0V100" stroke="#3A6DC5" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="#3A6DC5" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_407"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-green-on-white': {
    shape: 'plus',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_413)"> <rect width="100" height="100" fill="white"/> <path d="M50 0V100" stroke="#0F8657" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="#0F8657" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_413"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-red-on-white': {
    shape: 'plus',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_416)"> <rect width="100" height="100" fill="white"/> <path d="M50 0V100" stroke="#F94141" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="#F94141" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_416"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-white-on-blue': {
    shape: 'plus',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_395)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M50 0V100" stroke="white" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_395"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-white-on-green': {
    shape: 'plus',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_404)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M50 0V100" stroke="white" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_404"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-white-on-red': {
    shape: 'plus',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_401)"> <rect width="100" height="100" fill="#F94141"/> <path d="M50 0V100" stroke="white" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_401"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-white-on-yellow': {
    shape: 'plus',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_398)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M50 0V100" stroke="white" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_398"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'plus-yellow-on-white': {
    shape: 'plus',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_410)"> <rect width="100" height="100" fill="white"/> <path d="M50 0V100" stroke="#F7BF33" stroke-width="20"/> <path d="M100 50H3.93391e-06" stroke="#F7BF33" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_410"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-blue-on-white': {
    shape: 'quads',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_128)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="#3A6DC5"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="#3A6DC5"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="#3A6DC5"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="#3A6DC5"/> </g> <defs> <clipPath id="clip0_5_128"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-green-on-white': {
    shape: 'quads',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_143)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="#0F8657"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="#0F8657"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="#0F8657"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="#0F8657"/> </g> <defs> <clipPath id="clip0_5_143"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-red-on-white': {
    shape: 'quads',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_138)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="#F94141"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="#F94141"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="#F94141"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="#F94141"/> </g> <defs> <clipPath id="clip0_5_138"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-white-on-blue': {
    shape: 'quads',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_148)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="white"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="white"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="white"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_148"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-white-on-green': {
    shape: 'quads',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_153)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="white"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="white"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="white"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_153"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-white-on-red': {
    shape: 'quads',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_158)"> <rect width="100" height="100" fill="#F94141"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="white"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="white"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="white"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_158"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-white-on-yellow': {
    shape: 'quads',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_163)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="white"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="white"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="white"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="white"/> </g> <defs> <clipPath id="clip0_5_163"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'quads-yellow-on-white': {
    shape: 'quads',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_133)"> <rect width="100" height="100" fill="white"/> <path d="M0 0H25C38.8071 0 50 11.1929 50 25C50 38.8071 38.8071 50 25 50C11.1929 50 0 38.8071 0 25V0Z" fill="#F7BF33"/> <path d="M100 0V25C100 38.8071 88.8071 50 75 50C61.1929 50 50 38.8071 50 25C50 11.1929 61.1929 0 75 0H100Z" fill="#F7BF33"/> <path d="M0 100H25C38.8071 100 50 88.8071 50 75C50 61.1929 38.8071 50 25 50C11.1929 50 0 61.1929 0 75V100Z" fill="#F7BF33"/> <path d="M100 100V75C100 61.1929 88.8071 50 75 50C61.1929 50 50 61.1929 50 75C50 88.8071 61.1929 100 75 100H100Z" fill="#F7BF33"/> </g> <defs> <clipPath id="clip0_5_133"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-blue-on-white': {
    shape: 'square',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_60)"> <rect width="100" height="100" fill="white"/> <rect x="10" y="10" width="80" height="80" stroke="#3A6DC5" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_60"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-green-on-white': {
    shape: 'square',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_66)"> <rect width="100" height="100" fill="white"/> <rect x="10" y="10" width="80" height="80" stroke="#0F8657" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_66"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-red-on-white': {
    shape: 'square',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_64)"> <rect width="100" height="100" fill="white"/> <rect x="10" y="10" width="80" height="80" stroke="#F94141" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_64"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-white-on-blue': {
    shape: 'square',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_68)"> <rect width="100" height="100" fill="#3A6DC5"/> <rect x="10" y="10" width="80" height="80" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_68"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-white-on-green': {
    shape: 'square',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_74)"> <rect width="100" height="100" fill="#0F8657"/> <rect x="10" y="10" width="80" height="80" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_74"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-white-on-red': {
    shape: 'square',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_72)"> <rect width="100" height="100" fill="#F94141"/> <rect x="10" y="10" width="80" height="80" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_72"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-white-on-yellow': {
    shape: 'square',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_70)"> <rect width="100" height="100" fill="#F7BF33"/> <rect x="10" y="10" width="80" height="80" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_70"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'square-yellow-on-white': {
    shape: 'square',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_62)"> <rect width="100" height="100" fill="white"/> <rect x="10" y="10" width="80" height="80" stroke="#F7BF33" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_62"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-blue-on-white': {
    shape: 'x',
    scheme: 'blue-on-white',
    fg: 'blue',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_34)"> <rect width="100" height="100" fill="white"/> <path d="M0 100L100 0M100 100L0 0" stroke="#3A6DC5" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_34"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-green-on-white': {
    shape: 'x',
    scheme: 'green-on-white',
    fg: 'green',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_40)"> <rect width="100" height="100" fill="white"/> <path d="M0 100L100 0M100 100L0 0" stroke="#0F8657" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_40"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-red-on-white': {
    shape: 'x',
    scheme: 'red-on-white',
    fg: 'red',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_38)"> <rect width="100" height="100" fill="white"/> <path d="M0 100L100 0M100 100L0 0" stroke="#F94141" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_38"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-white-on-blue': {
    shape: 'x',
    scheme: 'white-on-blue',
    fg: 'white',
    bg: 'blue',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_26)"> <rect width="100" height="100" fill="#3A6DC5"/> <path d="M0 100L100 0M100 100L0 0" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_26"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-white-on-green': {
    shape: 'x',
    scheme: 'white-on-green',
    fg: 'white',
    bg: 'green',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_32)"> <rect width="100" height="100" fill="#0F8657"/> <path d="M0 100L100 0M100 100L0 0" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_32"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-white-on-red': {
    shape: 'x',
    scheme: 'white-on-red',
    fg: 'white',
    bg: 'red',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_30)"> <rect width="100" height="100" fill="#F94141"/> <path d="M0 100L100 0M100 100L0 0" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_30"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-white-on-yellow': {
    shape: 'x',
    scheme: 'white-on-yellow',
    fg: 'white',
    bg: 'yellow',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_28)"> <rect width="100" height="100" fill="#F7BF33"/> <path d="M0 100L100 0M100 100L0 0" stroke="white" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_28"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
  'x-yellow-on-white': {
    shape: 'x',
    scheme: 'yellow-on-white',
    fg: 'yellow',
    bg: 'white',
    svg: '<svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5_36)"> <rect width="100" height="100" fill="white"/> <path d="M0 100L100 0M100 100L0 0" stroke="#F7BF33" stroke-width="20"/> </g> <defs> <clipPath id="clip0_5_36"> <rect width="100" height="100" fill="white"/> </clipPath> </defs> </svg>',
  },
};

export const SHAPES: readonly PatternShape[] = [
  'arcs',
  'circle',
  'clover',
  'domes',
  'fans',
  'leaves',
  'plus',
  'quads',
  'square',
  'x',
];
export const COLORS: readonly PatternColor[] = ['blue', 'green', 'red', 'yellow'];
export const SCHEMES: readonly PatternScheme[] = [
  'blue-on-white',
  'green-on-white',
  'red-on-white',
  'yellow-on-white',
  'white-on-blue',
  'white-on-green',
  'white-on-red',
  'white-on-yellow',
];

export const PATTERN_IDS: readonly string[] = Object.keys(CATALOG);
