import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const svgDir = resolve(pkgRoot, 'svg');
const outFile = resolve(pkgRoot, 'src', 'catalog.ts');

const SHAPES = ['arcs', 'circle', 'clover', 'domes', 'fans', 'leaves', 'plus', 'quads', 'square', 'x'];
const COLORS = ['blue', 'green', 'red', 'yellow'];
const SCHEMES = [
  'blue-on-white',
  'green-on-white',
  'red-on-white',
  'yellow-on-white',
  'white-on-blue',
  'white-on-green',
  'white-on-red',
  'white-on-yellow',
];

function inlineSvg(filename) {
  const raw = readFileSync(resolve(svgDir, filename), 'utf8');
  return raw
    .replace(/<\?xml[^?]*\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function entries() {
  const files = readdirSync(svgDir).filter((f) => f.endsWith('.svg'));
  return files.map((filename) => {
    const base = filename.replace(/\.svg$/, '');
    const [shape, ...rest] = base.split('-');
    const scheme = rest.join('-');
    const [fg, , bg] = scheme.split('-');
    return {
      id: base,
      shape,
      scheme,
      fg,
      bg,
      svg: inlineSvg(filename),
    };
  });
}

function writeCatalog() {
  mkdirSync(dirname(outFile), { recursive: true });
  const items = entries();

  const escaped = items
    .map(
      (e) =>
        `  ${JSON.stringify(e.id)}: { shape: ${JSON.stringify(e.shape)}, scheme: ${JSON.stringify(
          e.scheme,
        )}, fg: ${JSON.stringify(e.fg)}, bg: ${JSON.stringify(e.bg)}, svg: ${JSON.stringify(e.svg)} }`,
    )
    .join(',\n');

  const content = `/* AUTO-GENERATED by scripts/generate-catalog.mjs. Do not edit by hand. */

export type PatternShape =
  ${SHAPES.map((s) => `| ${JSON.stringify(s)}`).join('\n  ')};

export type PatternColor = ${COLORS.map((c) => JSON.stringify(c)).join(' | ')};

export type PatternScheme =
  ${SCHEMES.map((s) => `| ${JSON.stringify(s)}`).join('\n  ')};

export interface PatternEntry {
  shape: PatternShape;
  scheme: PatternScheme;
  fg: string;
  bg: string;
  svg: string;
}

export const CATALOG: Record<string, PatternEntry> = {
${escaped}
};

export const SHAPES: readonly PatternShape[] = [${SHAPES.map((s) => JSON.stringify(s)).join(', ')}];
export const COLORS: readonly PatternColor[] = [${COLORS.map((c) => JSON.stringify(c)).join(', ')}];
export const SCHEMES: readonly PatternScheme[] = [${SCHEMES.map((s) => JSON.stringify(s)).join(', ')}];

export const PATTERN_IDS: readonly string[] = Object.keys(CATALOG);
`;

  writeFileSync(outFile, content, 'utf8');
  console.log(`✓ Generated catalog with ${items.length} patterns -> ${outFile}`);
}

writeCatalog();
